import { useState } from 'react'
import { apiConfigured,getSummary } from './api.js'

const sample={sessions:18420,views:52780,impressions:22640,clicks:1947,ctr:8.6,conversions:164,cvr:8.4,revenue:428600,rps:23,projects:[{name:'task-dashboard',status:'計測中',views:12840,ctr:15,conversions:71,revenue:168400},{name:'oshi-route-web',status:'計測中',views:10920,ctr:10.5,conversions:43,revenue:124800},{name:'korea-cheer-guide',status:'SDK待ち',views:8340,ctr:7.9,conversions:26,revenue:76800},{name:'taiwan-gourmet-map',status:'計測中',views:6920,ctr:7.6,conversions:17,revenue:39700},{name:'cosme-trip-app',status:'計測中',views:5110,ctr:7.2,conversions:7,revenue:18900}],funnel:[['アクセス',18420],['AI準備開始',12140],['準備完了',7360],['広告クリック',1947],['成果',164]],recommendations:['旅行準備完了後のホテル候補を出発日順に並べる','CTRが低い旅行用品枠を通信診断の直後へ移動する','台湾チア記事の通知CTAをA/Bテストする']}
const n=(value)=>new Intl.NumberFormat('ja-JP').format(value);const yen=(value)=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(value)

export default function App(){
  const [data,setData]=useState(sample);const [workspace,setWorkspace]=useState('ws-demo');const [key,setKey]=useState('');const [days,setDays]=useState(30);const [message,setMessage]=useState(apiConfigured?'管理キーで実測値へ切り替えられます。':'サンプルデータを表示中です。')
  const load=async()=>{try{setData(await getSummary(workspace,key,days));setMessage('実測データを表示しています。')}catch(error){setMessage(`取得できませんでした：${error.message}`)}}
  const max=Math.max(...data.funnel.map(([,value])=>value),1)
  return <main><header><a href="#top" className="logo"><i/>SUKIMA INSIGHT</a><nav><a href="#overview">概要</a><a href="#projects">全リポジトリ</a><a href="#improve">改善</a><a href="#pricing">料金</a></nav><button>GitHubを接続</button></header>
    <section className="hero" id="top"><p className="kicker">CROSS-REPOSITORY GROWTH PLATFORM</p><h1>公開したすべてを、<br/><em>数字で育てる。</em></h1><p>GitHub全リポジトリ、Web、PWA、アプリを一つの指標で比較。アクセスから売上まで、次に直す場所が分かります。</p><div><a href="#overview">ダッシュボードを見る</a><span>IPを保存しない・日次匿名セッション</span></div></section>
    <section className="dashboard" id="overview"><div className="toolbar"><div><p className="kicker">LIVE OVERVIEW</p><h2>成長ダッシュボード</h2></div><div><select value={days} onChange={(e)=>setDays(Number(e.target.value))}><option value="7">7日</option><option value="30">30日</option><option value="90">90日</option></select>{apiConfigured&&<><input value={workspace} onChange={(e)=>setWorkspace(e.target.value)} aria-label="ワークスペースID"/><input type="password" value={key} onChange={(e)=>setKey(e.target.value)} placeholder="管理キー"/><button onClick={load}>実測値を取得</button></>}<small>{message}</small></div></div>
      <div className="kpis">{[['アクセス数',n(data.sessions),'セッション'],['PV',n(data.views),'ページ表示'],['CTR',`${data.ctr}%`,`${n(data.clicks)}クリック`],['CVR',`${data.cvr}%`,`${n(data.conversions)}成果`],['売上',yen(data.revenue),'推定'],['RPS',yen(data.rps),'セッション収益']].map(([label,value,note])=><article key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</div>
      <div className="grid"><section className="panel"><p className="kicker">CONVERSION FUNNEL</p><h3>どこで離脱しているか</h3><div className="funnel">{data.funnel.map(([label,value],index)=><div key={label}><span>{label}</span><i><b style={{width:`${Math.max(2,value/max*100)}%`}}/></i><strong>{n(value)}</strong>{index>0&&<small>{data.funnel[index-1][1]?Math.round(value/data.funnel[index-1][1]*100):0}%</small>}</div>)}</div></section><aside className="panel improve" id="improve"><p className="kicker">IMPROVEMENT QUEUE</p><h3>次に直す3項目</h3><ol>{data.recommendations.map((item,index)=><li key={item}><b>0{index+1}</b><span>{item}</span></li>)}</ol><button>改善実験を作成</button></aside></div>
      <section className="panel repos" id="projects"><div className="panel-head"><div><p className="kicker">ALL GITHUB REPOSITORIES</p><h3>リポジトリ別パフォーマンス</h3></div><span>GitHub App接続後は追加・移管・削除を自動同期</span></div><div className="table"><div className="row heading"><span>プロジェクト</span><span>状態</span><span>PV</span><span>CTR</span><span>成果</span><span>売上</span></div>{data.projects.map((project)=><div className="row" key={project.name}><strong>{project.name}</strong><span><i className={project.status==='計測中'?'online':''}/>{project.status}</span><span>{n(project.views)}</span><span>{project.ctr}%</span><span>{n(project.conversions)}</span><span>{yen(project.revenue)}</span></div>)}</div></section>
    </section>
    <section className="pricing" id="pricing"><p className="kicker">PRICING MODEL</p><h2>実証してから、販売する。</h2><div>{[['Starter','3プロジェクト','基本KPI・週次レポート'],['Growth','30プロジェクト','収益・A/Bテスト・通知'],['Agency','複数顧客','権限・ホワイトラベル'],['Enterprise','全リポジトリ','SSO・監査ログ・SLA']].map(([name,limit,detail])=><article key={name}><b>{name}</b><strong>{limit}</strong><p>{detail}</p><a href="mailto:hello@sukima-insight.jp">相談する →</a></article>)}</div></section>
    <footer><a href="#top" className="logo"><i/>SUKIMA INSIGHT</a><p>Privacy-first analytics for every product.</p><span>© 2026 SUKIMA INSIGHT</span></footer>
  </main>
}
