import { useState } from 'react'
import { apiConfigured,getGithubStatus,getSummary,syncGithub } from './api.js'
import './Onboarding.css'

const sample={sessions:18420,views:52780,impressions:22640,clicks:1947,ctr:8.6,conversions:164,cvr:8.4,revenue:428600,rps:23,projects:[{name:'task-dashboard',status:'計測中',views:12840,ctr:15,conversions:71,revenue:168400},{name:'oshi-route-web',status:'計測中',views:10920,ctr:10.5,conversions:43,revenue:124800},{name:'korea-cheer-guide',status:'SDK待ち',views:8340,ctr:7.9,conversions:26,revenue:76800},{name:'taiwan-gourmet-map',status:'計測中',views:6920,ctr:7.6,conversions:17,revenue:39700}],funnel:[['アクセス',18420],['AI準備開始',12140],['準備完了',7360],['広告クリック',1947],['成果',164]],recommendations:['旅行準備完了後のホテル提案を出発日順に並べる','CTRが低い旅行用品を通信診断の直後へ移動する','台湾チア記事の共通CTAをA/Bテストする']}
const n=(v)=>new Intl.NumberFormat('ja-JP').format(v),yen=(v)=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(v),githubSlug=import.meta.env.VITE_GITHUB_APP_SLUG||''

export default function App(){const [data,setData]=useState(sample),[workspace,setWorkspace]=useState('ws-demo'),[key,setKey]=useState(''),[days,setDays]=useState(30),[github,setGithub]=useState(null),[message,setMessage]=useState(apiConfigured?'管理キーを入力すると実測値へ切り替わります。':'デモデータを表示しています。');const load=async()=>{try{const [summary,status]=await Promise.all([getSummary(workspace,key,days),getGithubStatus(workspace,key)]);setData(summary);setGithub(status);setMessage('最新データを表示しています。')}catch(error){setMessage(`取得できませんでした: ${error.message}`)}};const synchronize=async()=>{try{const result=await syncGithub(workspace,key);setMessage(`${result.synced}件を同期しました。`);setGithub(await getGithubStatus(workspace,key))}catch(error){setMessage(`同期できませんでした: ${error.message}`)}};const max=Math.max(...data.funnel.map(([,v])=>v),1),installUrl=githubSlug?`https://github.com/apps/${githubSlug}/installations/new`:'#setup';return <main>
<header><a href="#top" className="logo"><i/>SUKIMA INSIGHT</a><nav><a href="#overview">概要</a><a href="#setup">導入</a><a href="#projects">全リポジトリ</a><a href="#pricing">料金</a></nav><a className="header-action" href={installUrl}>GitHubを接続</a></header>
<section className="hero" id="top"><p className="kicker">CROSS-REPOSITORY GROWTH PLATFORM</p><h1>公開したすべてを、<br/><em>数字で育てる。</em></h1><p>GitHubの全サイト・Web・PWA・アプリを一つの指標で比較。アクセスから収益まで、次に直す場所が分かります。</p><div><a href="#overview">ダッシュボードを見る</a><span>IPを保存しない日次匿名セッション</span></div></section>
<section className="dashboard" id="overview"><div className="toolbar"><div><p className="kicker">LIVE OVERVIEW</p><h2>成果ダッシュボード</h2></div><div><select value={days} onChange={(e)=>setDays(Number(e.target.value))}><option value="7">7日</option><option value="30">30日</option><option value="90">90日</option></select>{apiConfigured&&<><input value={workspace} onChange={(e)=>setWorkspace(e.target.value)} aria-label="ワークスペースID"/><input type="password" value={key} onChange={(e)=>setKey(e.target.value)} placeholder="管理キー"/><button onClick={load}>実測値を取得</button></>}<small>{message}</small></div></div>
<div className="kpis">{[['アクセス数',n(data.sessions),'セッション'],['PV',n(data.views),'ページ表示'],['CTR',`${data.ctr}%`,`${n(data.clicks)}クリック`],['CVR',`${data.cvr}%`,`${n(data.conversions)}成果`],['売上',yen(data.revenue),'推定'],['RPS',yen(data.rps),'セッション収益']].map(([l,v,note])=><article key={l}><span>{l}</span><strong>{v}</strong><small>{note}</small></article>)}</div>
<div className="grid"><section className="panel"><p className="kicker">CONVERSION FUNNEL</p><h3>どこで離脱しているか</h3><div className="funnel">{data.funnel.map(([l,v],i)=><div key={l}><span>{l}</span><i><b style={{width:`${Math.max(2,v/max*100)}%`}}/></i><strong>{n(v)}</strong>{i>0&&<small>{data.funnel[i-1][1]?Math.round(v/data.funnel[i-1][1]*100):0}%</small>}</div>)}</div></section><aside className="panel improve"><p className="kicker">IMPROVEMENT QUEUE</p><h3>次に直す項目</h3><ol>{data.recommendations.map((item,i)=><li key={item}><b>0{i+1}</b><span>{item}</span></li>)}</ol></aside></div>
<section className="panel setup" id="setup"><div><p className="kicker">3-STEP ONBOARDING</p><h3>全リポジトリを自動で取り込む</h3><p>① GitHub Appをインストール　② 計測SDKを追加　③ 成果イベントを送信</p></div><div className="connection"><strong>{github?.installations?.length?'接続済み':'未接続'}</strong><span>{github?`${github.repositoryCount}件同期・最終 ${github.installations[0]?.last_synced_at?new Date(github.installations[0].last_synced_at).toLocaleString('ja-JP'):'未同期'}`:'管理キーで状態を確認できます'}</span>{github?.installations?.length?<button onClick={synchronize}>今すぐ同期</button>:<a href={installUrl}>GitHub Appを導入</a>}</div></section>
<section className="panel repos" id="projects"><div className="panel-head"><div><p className="kicker">ALL GITHUB REPOSITORIES</p><h3>リポジトリ別パフォーマンス</h3></div><span>追加・移管・削除をGitHub Appで自動同期</span></div><div className="table"><div className="row heading"><span>プロジェクト</span><span>状態</span><span>PV</span><span>CTR</span><span>成果</span><span>売上</span></div>{data.projects.map((p)=><div className="row" key={p.name}><strong>{p.name}</strong><span><i className={p.status==='計測中'?'online':''}/>{p.status}</span><span>{n(p.views)}</span><span>{p.ctr}%</span><span>{n(p.conversions)}</span><span>{yen(p.revenue)}</span></div>)}</div></section></section>
<section className="pricing" id="pricing"><p className="kicker">PRICING MODEL</p><h2>実証してから、販売する。</h2><div>{[['Starter','3プロジェクト','基本KPI・週次レポート'],['Growth','30プロジェクト','収益・A/Bテスト・通知'],['Agency','複数顧客','権限・ホワイトラベル'],['Enterprise','全リポジトリ','SSO・監査ログ・SLA']].map(([name,limit,detail])=><article key={name}><b>{name}</b><strong>{limit}</strong><p>{detail}</p><a href="mailto:hello@sukima-insight.jp">相談する →</a></article>)}</div></section><footer><a href="#top" className="logo"><i/>SUKIMA INSIGHT</a><p>Privacy-first analytics for every product.</p><span>© 2026 SUKIMA INSIGHT</span></footer></main>}
